[package]
name = "card-table"
version = "0.1.0"
authors = ["mnussbaum <michaelnussbaum08@gmail.com>"]
edition = "2018"

[dependencies]
diesel= {version = "1.4", features = ["postgres", "chrono"]}
dotenv = "0.15"
rand = "0.7"
rocket = "0.4.6"
rocket_contrib = {version="0.4.6", features=["json", "diesel_postgres_pool"]}
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
text_io = "0.1"
uuid = {version = "0.8.2", features = ["v4"]}
