[package]
name = "card-game"
version = "0.1.0"
authors = ["mnussbaum <michaelnussbaum08@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
text_io = "0.1"
